//INFO: generate files for a site from json read from stdin (generated by file2json.js)
//U: m -Rf _site xjson2file xsrc ; cat x.json | node src/lib/js/json2file.js xsrc

const fs = require("fs");
const yaml = require("js-yaml");
const matter= require('gray-matter');
const util = require("./util.js");

const data = JSON.parse(fs.readFileSync(0, 'utf-8'));
const dst= process.argv[2] || 'xjson2file';
fs.mkdirSync(dst,{recursive: true});

Object.entries(data).forEach(([fn,d]) => { if (!d) return;
	let content;
	if (d.bin) { content= "XXX bin copy "+fn; } 
	else if (fn.match(/\.((yaml))$/)) { content= yaml.dump(d.data) } 
	else if (fn.match(/\.((json))$/)) { content= JSON.stringify(d.data,0,2) }
	else if (fn.match(/\.((njk)|(md)|(html)|(txt)|(csv)|(js)|(svg))$/)) {
		content= matter.stringify(d);
	}
	else { console.log("ERROR: unknown type",fn) }
	if(content) {
		util.set_file(dst+'/'+fn, content);	
	}
})
